name: UniCorn-P4 build

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: UniCorn-P4 CI
      run: cd docker && docker-compose build